### ISSUE TITLE
NOT ISSUE

### ISSUE THREAD

**Issue by kuatroka** [tmcw/bikesharecharts#17]
Hi, first of all sorry, but it's not an issue. I don't see a discussions option, so I decided to post it here. 

I'm trying to use your code to understand how can I access, initialize, read and do select on  a parquet file sitting in a local directory and for the life of me I can't figure it out. Could you please highlight the lines of code that, initiate the DB, import a **local to the server** (not the user) parquet file and some dummy select statement that gets exposed to the return statement of some dummy function and can be reused in the Sveltekit's `let export data` ? Thanks

 I tried to use the `summary` route for my example case and there should be a `./data.parquet` as I understand it, but there isn't any and it looks like this route doesn't seem to work when running the app. It's just an empty page.

**Comment by tmcw** [comment]
Hi! No problem - this project currently uses duckdb-wasm exclusively, it's not using duckdb on the server at all. So the import of the parquet file is against a hosted file on HTTP, not a file that's local to the server.

DuckDB is configured here: https://github.com/tmcw/bikesharecharts/blob/c49733b9326b8de10296f94e3638a015ee4e6b60/web/src/lib/duckdb.ts

And the data is loaded here:

https://github.com/tmcw/bikesharecharts/blob/c49733b9326b8de10296f94e3638a015ee4e6b60/web/src/routes/%2Bpage.svelte#L31

The data is not in the GitHub repo because the produced data is very large and would be inefficient to store, update, and move around in git - instead the data is stored in R2.

If you're loading data on the server side, the process is different - [like these docs describe](http://duckdb.org/docs/archive/0.8.1/guides/import/parquet_import).

I feel your pain - getting parquet and duckdb to play nice together was a challenge!

**Comment by kuatroka** [comment]
> I feel your pain - getting parquet and duckdb to play nice together was a challenge!
I wanna cry here.. 

###
1. Thanks for the explanation. I still don't get it fully, but I understood your architecture better now. 
What about this piece of code from the `summary` [route](https://github.com/tmcw/bikesharecharts/blob/c49733b9326b8de10296f94e3638a015ee4e6b60/web/src/routes/summary/%2Bpage.svelte) ? Where/what is the `./data.parquet` files is and where does it lives?
![image](https://github.com/tmcw/bikesharecharts/assets/9093546/91c24f61-db29-4a66-8ada-1659e4e9c213)

**Comment by tmcw** [comment]
The summary route's currently broken - that data isn't currently there, best to ignore that file for now.

**Comment by kuatroka** [comment]
I'm curious about the logic. Were that file sitting in the `summary` folder, would it be picked up by the `return conn` so it could be ran queries against? Thanks

**Comment by tmcw** [comment]
Yes, because it's registered with the following line in which I called `registerFileBuffer`. It'd be available as a table called `station_status.parquet`.

**Comment by kuatroka** [comment]
Thanks a lot!
